name: Flutter Nightly Build Linux arm

on: workflow_dispatch


jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build-linux-arm.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly" 
